Add Github action to build and push docker image to Docker hub
GeoscienceAustralia/dea-coastlines pull request #65
Opened 2022-09-26 06:41 UTC by robbibt

This PR adds a simple Github actions workflow for building the Coastlines Docker image.

Instead of copying the more complex [DE Africa workflow](https://github.com/digitalearthafrica/deafrica-coastlines/blob/main/.github/workflows/built-test-docker.yaml), I copied the approach from the internal docs guide and `dea-conflux` because I liked how simple they were:

- https://docs.dev.dea.ga.gov.au/procedures/containerised_generic_deployment.html#id2
- https://github.com/GeoscienceAustralia/dea-conflux/blob/main/.github/workflows/push.yml

I'm not sure if I've missed anything important by doing this, but the first run seems to successfully run on Github actions: 
https://github.com/GeoscienceAustralia/dea-coastlines/actions/runs/3125343974/jobs/5069615404

And the image itself is visible on Dockerhub:
https://hub.docker.com/layers/geoscienceaustralia/dea-coastlines/0.0.1/images/sha256-18185f55f3445ff1b145370f5c42bec62fc49f2d1ee6269602cf873f22105d0f?context=explore

This is my first time using Github Actions, so would appreciate any feedback! 😃

2022-09-26 07:23 UTC, pindge requested changes

2022-09-26 07:23 UTC, pindge commented on .github/workflows/docker.yaml
> +      - '.github/workflows/docker.yml'
file is yaml

2022-09-26 07:23 UTC, pindge commented on .github/workflows/docker.yaml
> +    - name: Get git commit hash for push to branch
insert a comment and blank line for readablity

2022-09-26 07:23 UTC, pindge commented on .github/workflows/docker.yaml
> +    - name: Get tag for this build if it exists
this name isnt describing what this step does

2022-09-27 01:05 UTC, robbibt commented on .github/workflows/docker.yaml
> +    - name: Get tag for this build if it exists
Updated; hopefully I have described this better this time!

2022-09-27 01:14 UTC, pindge approved these changes

2022-09-27 01:41 UTC, merged